import { PrintField, PrintFieldType, ScanResult } from "./types";

export function mockScanResult(packageRoot: string): ScanResult {
  return {
    packageRoot,
    streamingAssets: `${packageRoot}\\CardMaker_Data\\StreamingAssets`,
    cards: [
      {
        id: "1002",
        game: "CHU",
        recordType: "Card",
        dataName: "card00001002",
        displayName: "Sample CHU Character",
        characterName: "Sample CHU Character",
        skillName: "Technical Challenge",
        skillText: "COMBO and CHAIN bonuses are printed on the final surface.",
        rareType: 2,
        labelType: 3,
        difType: 0,
        miss: 0,
        combo: 150,
        chain: 300,
        imagePath: null,
        thumbnailPath: null,
        assetLayers: [],
        sourceXml: "Browser fallback",
        editableFields: ["characterName", "skillName", "skillText"],
        printFields: [
          pf("characterName", "Character name", "text", "Sample CHU Character"),
          pf("skillName", "Skill name", "text", "Technical Challenge"),
          pf("skillText", "Skill description", "multiline", "COMBO and CHAIN bonuses are printed on the final surface."),
          pf("serialId", "Serial ID", "text", "A000-0000-0000"),
          pf("rareType", "Rare type", "metadata", "2"),
          pf("labelType", "Label type", "number", "3"),
          pf("difType", "Difficulty type", "number", "0"),
          pf("miss", "MISS count", "number", "0"),
          pf("combo", "COMBO count", "number", "150"),
          pf("chain", "CHAIN count", "number", "300"),
          pf("holo", "Holographic print", "metadata", "false"),
          pf("hideParam", "Hide score parameters", "bool", "false"),
          pf("hideSerialId", "Hide serial", "bool", "false"),
          pf("hideBackGround", "Hide background label", "bool", "false"),
          pf("hideChara", "Hide character", "bool", "false"),
        ],
      },
      {
        id: "1",
        game: "MAI",
        recordType: "CardType",
        dataName: "cardtype000004",
        displayName: "Sample MAI Gold Pass",
        characterName: "Sample MAI Gold Pass",
        skillName: "Pass",
        skillText: "The renderer combines player name, rating, QR, serial, period, and card frame.",
        rareType: null,
        labelType: null,
        difType: null,
        miss: null,
        combo: null,
        chain: null,
        imagePath: null,
        thumbnailPath: null,
        assetLayers: [],
        sourceXml: "Browser fallback",
        editableFields: ["characterName", "skillName", "skillText"],
        printFields: [
          pf("userName", "Player name", "text", "PLAYER"),
          pf("rating", "Rating", "number", "12345"),
          pf("friendCode", "Friend code", "text", "0000-0000-0000"),
          pf("hasFriendCode", "Print friend code", "bool", "true"),
          pf("charaName", "Character/card name", "text", "Sample MAI Gold Pass"),
          pf("cardKind", "Card type", "metadata", "Pass"),
          pf("effectText", "Effect text", "metadata", "The renderer combines player name, rating, QR, serial, period, and card frame."),
          pf("endDate", "End date", "text", "2099/12/31"),
          pf("serialId", "Serial ID", "text", "M000-0000-0000"),
          pf("verCharaId", "Version character ID", "text", "[maimaiDX]1.00-0001"),
          pf("qrPayload", "QR text override", "multiline", ""),
          pf("cardId", "Card ID", "number", "1012"),
          pf("typeId", "Type ID", "number", "4"),
          pf("charaId", "Character ID", "number", "101"),
          pf("cardTypeParamId", "Card type parameter ID", "number", "200"),
          pf("mapBonus", "Map bonus", "text", "GoldBonus"),
          pf("extendBitParameter", "Effect bit flags", "number", "3"),
          pf("holo", "Holographic print", "metadata", "true"),
          pf("hideSerialAndQR", "Hide serial and QR", "bool", "false"),
          pf("hidePlayerName", "Hide player name", "bool", "false"),
          pf("hideRating", "Hide rating", "bool", "false"),
          pf("hideFrame", "Hide frame", "bool", "false"),
          pf("hideCardIcon", "Hide card icon", "bool", "false"),
          pf("hideCharaNameAndPeriod", "Hide name and period", "bool", "false"),
          pf("hideFriendCode", "Hide friend code", "bool", "false"),
          pf("hideChara", "Hide character", "bool", "false"),
        ],
      },
      {
        id: "100001",
        game: "MU3",
        recordType: "Card",
        dataName: "mu3_sample_100001",
        displayName: "Sample MU3 Character",
        characterName: "Sample MU3 Character",
        skillName: "Attack Boost",
        skillText: "Boosts printed attack and limit break indicators.",
        rareType: 2,
        labelType: null,
        difType: null,
        miss: null,
        combo: null,
        chain: null,
        imagePath: null,
        thumbnailPath: null,
        assetLayers: [],
        sourceXml: "Browser fallback",
        editableFields: ["characterName", "skillName", "skillText"],
        printFields: [
          pf("userName", "User name", "text", "USER"),
          pf("characterName", "Character name", "text", "Sample MU3 Character"),
          pf("baseCharacterName", "Base character name", "metadata", "Sample MU3 Character"),
          pf("nameForCommonModel", "Common model name", "metadata", "Common Model"),
          pf("isCommonModel", "Common model", "metadata", "true"),
          pf("nickName", "Nickname", "text", "Sample Title"),
          pf("ipName", "IP / school", "text", "Sample School"),
          pf("skillName", "Skill name", "text", "Attack Boost"),
          pf("skillText", "Skill description", "multiline", "Boosts printed attack and limit break indicators."),
          pf("serialId", "Serial ID", "text", "U000-0000-0000"),
          pf("qrPayload", "QR payload", "multiline", ""),
          pf("cardNo", "Card number", "text", "No. 100001"),
          pf("maxAttack", "Max attack", "number", "312"),
          pf("levelParams", "Level parameters", "text", "100,160,190,220,250,280,300,310,312,340"),
          pf("ownCount", "Own count", "number", "3"),
          pf("awaken", "Awaken state", "number", "1"),
          pf("rareType", "Rarity", "number", "2"),
          pf("attribute", "Attribute", "number", "0"),
          pf("holo", "Holographic print", "bool", "true"),
          pf("sign", "Signed card", "metadata", "false"),
          pf("hideAttrRarity", "Hide attribute and rarity", "bool", "false"),
          pf("hideAttackLimit", "Hide attack limit", "bool", "false"),
          pf("hideSkill", "Hide skill", "bool", "false"),
          pf("hideGrade", "Hide grade", "bool", "false"),
          pf("hideFrame", "Hide frame", "bool", "false"),
          pf("hideName", "Hide names", "bool", "false"),
          pf("hideAwaken", "Hide awaken", "bool", "false"),
          pf("hideUserName", "Hide user name", "bool", "false"),
          pf("hideQRCode", "Hide QR code", "bool", "false"),
          pf("hideCardNo", "Hide card number", "metadata", "false"),
        ],
      },
    ],
    stats: {
      chuCards: 1,
      maiCards: 0,
      maiCardTypes: 1,
      maiCardCharas: 0,
      mu3AssetCards: 0,
      mu3XmlRecords: 1,
      pngAssets: 2,
      unityBundles: 0,
      unityBundleBytes: 0,
    },
    warnings: [],
  };
}

export function pf(key: string, label: string, fieldType: PrintFieldType, value: string): PrintField {
  return { key, label, fieldType, value };
}

